// ACCOUNT ACTION TYPES
export const FETCH_ACCOUNTS = "FETCH_ACCOUNTS";
export const FETCH_ACCOUNTS_SUCCESS = "FETCH_ACCOUNTS_SUCCESS";
export const FETCH_ACCOUNTS_FAIL = "FETCH_ACCOUNTS_FAIL";

// GLOBAL TASKS ACTION TYPES
export const FETCH_TASKS_USER = "FETCH_TASKS_USER";
export const FETCH_TASKS_SUCCESS_USER = "FETCH_TASKS_SUCCESS_USER";
export const FETCH_TASKS_FAIL_USER = "FETCH_TASKS_FAIL_USER";

// ACCOUNT SPECIFIC ACTION TYPES
export const FETCH_TASKS_ACCOUNT = "FETCH_TASKS_ACCOUNT";
export const FETCH_TASKS_ACCOUNT_SUCCESS = "FETCH_TASKS_ACCOUNT_SUCCESS";
export const FETCH_TASKS_ACCOUNT_FAIL = "FETCH_TASKS_ACCOUNT_FAIL";

// SNAPSHOT ACTION TYPES
export const FETCH_SNAPSHOTS_ACCOUNT = "FETCH_SNAPSHOTS_ACCOUNT";
export const FETCH_SNAPSHOTS_ACCOUNT_SUCCESS =
  "FETCH_SNAPSHOTS_ACCOUNT_SUCCESS";
export const FETCH_SNAPSHOTS_ACCOUNT_FAIL = "FETCH_SNAPSHOTS_ACCOUNT_FAIL";
